name: Gradr

on:
  issues:
    types:
      - closed

jobs:
  autograde:
    name: Test & Auto-grade Cloud Challenge
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      GRADR_TOKEN: ${{ secrets.GRADR_TOKEN }}
      ISSUE_URL: ${{ github.event.issue.html_url }}
      ISSUE_BODY: ${{ github.event.issue.body }}
    
    steps:
      - name: Checkout Your Repo
        uses: actions/checkout@v2

      - name: Prepare Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Acquire Audits
        uses: actions/checkout@v2
        with: 
          repository: pipeline-v2-eligibility/audits
          path: audits

      - name: Test Cloud Task
        run: |
          npm install --location=global yarn
          cd audits
          git pull --no-rebase
          echo "GH_TOKEN=${GRADR_TOKEN}" > .env
          yarn install
          yarn audit-cloud

      - name: Report Audits
        if: always()
        uses: pipeline-v2-eligibility/jest-to-sheets@v2
        with:
          track: 'cloud'
          server: https://api.sheetson.com/v2/sheets
          sheetid: 1TpZp5pXOGDNhODDvbbjEffXopljG0MPdLxl0RVFY3yo
          token: HXlur8K20ZpoB-6FNsnSUtj2kGoDqCDHDl8vZBdLtQCv9UFOVhMsM2IBwD8
          properties: ${{ github.workspace }}/properties.json